<!--
This is for including Chapter 1.  Notice that it's also good practice to name your chunk.  This will help you debug potential issues as you knit.  The chunk above is called intro and the one below is called chapter1.  Feel free to change the name of the Rmd file as you wish, but don't forget to change it here from chap1.Rmd.
-->
<!--
The {#rmd-basics} text after the chapter declaration will allow us to link throughout the document back to the beginning of Chapter 1.  These labels will automatically be generated (if not specified) by changing the spaces to hyphens and capital letters to lowercase.  Look for the reference to this label at the beginning of Chapter 2.
-->

# O setor elétrico

É importante, antes de partir para o estudo de caso em questão, estabelecer o contexto do trabalho em questão. De fato, neste capítulo serão tratados os fundamentos do setor elétrico no Brasil, desde os órgãos aos produtos principais do setor, como o Plano Decenal de Expansão (PDE), que contemplam o presente estudo.

## Órgãos presentes no estudo

### MME

O Ministério de Minas e Energia (MME) foi criado em pela Lei nº 3.782/1960, no governo do presidente Juscelino Kubitschek, e posteriormente regulamentado pelo Decreto nº 50.390/1961. Assim seguiu por 30 anos, até ser extinto em 1990 e recriado em 1992.

Logo em seguida, com a Lei nº 10.683/2003, foram definidas as competências do MME como sendo as áreas de:

- Geologia, recursos minerais e energéticos;
- Aproveitamento da energia hidráulica; mineração e metalurgia; e
- Petróleo, combustível e energia elétrica.

O MME tem como empresas vinculadas a Eletrobras e a Petrobras. Estão, também, vinculadas algumas autarquias ao Ministério, dentre elas: a Agência Nacional de Energia Elétrica (ANEEL); Agência Nacional do Petróleo, Gás Natural e Biocombustíveis (ANP); e a Agência Nacional de Mineração (ANM).

### ANEEL

A Agência Nacional de Energia Elétrica (ANEEL) é uma autarquia vinculada ao Ministério de Minas e Energia. Tem como finalidade regular e fiscalizar a produção, transmissão, distribuição e comercialização de energia elétrica, de acordo com a legislação e em conformidade com as diretrizes e as políticas do governo federal. A autarquia foi criada pela Lei nº 9.427/1996, durante o mandato de Fernando Henrique Cardoso.

Especificamente, a ANEEL é responsável por:

- Cálculo e revisão de tarifas de distribuição, transmissão e geração (no caso das usinas cuja energia tem preço regulado);
- Estabelecimento de condições gerais para contratação de acesso e uso de instalações de transmissão e distribuição de energia por concessionárias e consumidores;
- Promoção de leilões para licitação de concessões de serviço público de geração, transmissão e distribuição de energia elétrica, bem como a concessão de uso de potenciais hidráulicos, seguindo as diretrizes emitidas pelo MME;
- Gestão de contratos de concessão ou de permissão para serviços públicos de energia elétrica e supervisão de todas as instalações do sistema;
- Definição de regras de participação na CCEE e ratificação da Convenção de Comercialização para seus membros; e
- Autorização de atividades do ONS.
As decisões da ANEEL são tomadas por uma diretoria composta por cinco diretores com mandatos de quatro anos não coincidentes. Os diretores são nomeados pelo Presidente da República e confirmados pelo Senado. A ANEEL pode entrar em acordo com agências reguladoras estaduais para delegar algumas de suas funções.^[Vários estados têm suas próprias agências reguladoras de serviço público. Essas agências só podem regular os serviços de eletricidade se tiverem autorização da ANEEL para fazê-lo. A ANEEL geralmente os autoriza a tratar de assuntos como reclamações de consumidores, mas nunca com questões regulatórias, reajustes tarifários ou revisões.]

Pode-se conferir a lista completa de atribuições pelo Art. 3° da Lei n° 9.427/1996.

### ONS

O Operador Nacional do Sistema Elétrico (ONS) é uma entidade privada sem fins lucrativos que é responsável pela coordenação e controle da operação de instalações de geração e transmissão de energia elétrica do Sistema Interligado Nacional (SIN), sob fiscalização da ANEEL. O órgão foi criado pela Lei nº 9.648/1998, com alterações introduzidas pela Lei nº 10.848/2004 e regulamentado pelo Decreto nº 5.081/2004.

O ONS determina e supervisiona o despacho real do sistema (“despacho físico”) e os dados necessários para o chamado “despacho comercial”, que é utilizado para liquidação financeira no mercado de curto prazo.^[O despacho físico leva em consideração as restrições elétricas em todos os caminhos da rede de transmissão, bem como as características técnicas e a disponibilidade de geradores e cargas. Por outro lado, mantendo o mesmo modelo para geradores, o despacho comercial possui um modelo simplificado para cargas e a rede de transmissão: cargas são agrupadas em regiões, também conhecidas como submercados e restrições de transmissão dentro dos submercados são negligenciadas; restrições de transmissão entre submercados são mantidas.]

O ONS possui ainda outras funções, tais como:

- Realizar o planejamento operacional, programação e despacho da geração do sistema, otimizando o uso de recursos levando em consideração a confiabilidade do sistema;
- Manter centros de controle para supervisão e coordenação do sistema;
- Supervisionar e controlar a operação do sistema nacional de energia elétrica interligado e interconexões com países vizinhos;
- Gerir serviços de transmissão de energia elétrica, incluindo serviços ancilares e suas condições de acesso;
- Propor novas adições à rede básica (transmissão), bem como reforços às instalações de transmissão existentes; e
- Definir as regras operacionais para as instalações de transmissão da Rede Básica a serem aprovadas pela ANEEL.

O ONS é composto por membros associados e membros participantes, que são as empresas de geração, transmissão, distribuição, consumidores livres, importadores e exportadores de energia. Também participam o Ministério de Minas e Energia (MME) e representantes dos Conselhos de Consumidores.

### CCEE

A Câmara de Comercialização de Energia Elétrica (CCEE) tem por finalidade viabilizar a comercialização de energia elétrica no mercado de energia brasileiro. De fato, esta efetua a contabilização e a liquidação financeira das operações realizadas no mercado de curto prazo. As regras e procedimentos que regulam as atividades realizadas pela CCEE são aprovadas pela ANEEL.

Foi criada pela Lei nº 10.848/2004, sob mandato do presidente Luiz Inácio Lula da Silva, sucedendo ao antigo Mercado Atacadista de Energia, e é regulamentada pelo Decreto nº 5.177/2004.

Trata-se de um órgão técnico que faz a compensação entre o que foi feito e o que está programado. Por exemplo, quando uma distribuidora utiliza a energia do sistema integrado, ela não sabe quem está fornecendo-a, podendo ser hidrelétricas, em períodos normais, ou termelétricas, em períodos de seca. Nesse segundo caso, o valor da energia se torna mais caro.

Cabe à CCEE apurar essas questões, além da compra e venda de energia. Outro ponto que é responsabilidade da CCEE é determinar os créditos e débitos dos agentes envolvidos no mercado livre de energia. Por fim, a CCEE promove leilões de compra e venda, gerenciando os seus contratos.

### EPE

A Empresa de Pesquisa Energética (EPE) é uma empresa pública vinculada ao Ministério de Minas e Energia, criada pela Lei 10.847/2004, sob mandato do ex-presidente Luiz Inácio Lula da Silva. Tem por finalidade prestar serviços na área de estudos e pesquisas destinadas a subsidiar o planejamento do setor energético.

Cabe à EPE, dentre outras atribuições:

- Formular estudos para a definição da matriz energética, com indicação de estratégias a serem perseguidas e metas a serem atingidas no longo prazo;
- Realizar estudos técnicos para (novos) leilões de expansão da oferta de energia, incluindo o cálculo das Garantias Físicas;
- Realizar estudos para planejamento integrado de recursos energéticos;
- Preparar estudos de expansão do sistema (geração e transmissão), incluindo os planos de expansão de 10 anos da geração e transmissão;^[A expansão do sistema de distribuição é de responsabilidade de cada distribuidora. De acordo com a regulamentação atual, os investimentos feitos pelas distribuidoras para atender às necessidades de expansão são auditados pela ANEEL (durante a revisão tarifária) para verificar se eles eram “realmente necessários”.]
- Promover estudos de potencial energético, incluindo estudos de viabilidade de bacias hidrográficas;
- Obter a licença ambiental prévia necessária para os leilões de novos projetos de transmissão e hidrelétricos e, no caso dos últimos, também a declaração de disponibilidade hidráulica; e
- Verificar a solidez técnica dos projetos de geração, a fim de habilitá-los a participar dos leilões regulados para o mercado cativo.

A lista completa de atribuições pode ser vista no Art. 4° da Lei n° 10.847/2004.

Uma das principais motivações para a criação da EPE foram os racionamentos e apagões ocorridos no início da década, ocorridos durante o governo de Fernando Henrique Cardoso, atribuídos em parte à carência de planejamento. Embora seja uma entidade independente, é vinculada ao Ministério de Minas e Energia.

### CNPE

O Conselho Nacional de Política Energética (CNPE), criado pela Lei nº 9.478/1997, na condição de órgão de assessoramento do Presidente da República, é destinado à formulação de políticas e diretrizes energéticas.

Dispõe sobre a estrutura e funcionamento desse Conselho o Decreto nº 3.520/2000, com detalhes sobre sua posterior transformação em órgão de assessoramento imediato do Presidente da República na Lei nº 10.683/2003.

### CMSE

O Comitê de Monitoramento do Setor Elétrico (CMSE) é um comitê governamental que lida com assuntos referentes à energia elétrica a nível federal. Foi criado pela Lei nº 10.848/2004 e regulamentado pelo Decreto nº 5.175/2004. De acordo com o Art. 3º deste decreto, compete ao CMSE:

- Acompanhar o desenvolvimento das atividades de geração, transmissão, distribuição, comercialização, importação e exportação de energia elétrica, gás natural e petróleo e seus derivados;
- Avaliar as condições de abastecimento e de atendimento, relativamente às atividades que desenvolvam o fornecimento eletroenergético, em horizontes pré-determinados;
- Realizar periodicamente análise integrada de segurança de abastecimento e atendimento ao mercado de energia elétrica, de gás natural e petróleo e seus derivados;
- Identificar dificuldades e obstáculos de caráter técnico, ambiental, comercial, institucional e outros que afetem, ou possam afetar, a regularidade e a segurança de abastecimento e atendimento à expansão dos setores de energia elétrica, gás natural e petróleo e seus derivados; e
- Elaborar propostas de ajustes, soluções e recomendações de ações preventivas ou saneadoras de situações observadas em decorrência de atividades que possam criar dificuldades e obstáculos ao setor energético, visando à manutenção ou restauração da segurança no abastecimento e no atendimento eletroenergético, encaminhando-as, quando for o caso, ao Conselho Nacional de Política Energética - CNPE.

## O fluxo de energia

Atualmente, o setor elétrico brasileiro tem uma estrutura predominantemente unidirecional nos fluxos de energia. Assim, são tipicamente divididos em geração, transmissão, comercialização e distribuição. Por se tratarem do final da cadeia de valor convencional, os consumidores então têm efetivamente um comportamento passivo.

A geração de energia elétrica é a transformação da energia primária -- petróleo, carvão mineral, dentre outros -- em energia elétrica. No Brasil, predomina-se a geração hidráulica devido ao grande potencial hidroenergético dos nossos rios.

Os geradores são remunerados pela energia que vendem a seus clientes através de contratos ou através da liquidação no Mercado de Curto Prazo. Suas receitas são utilizadas, dentre outros, para amortizar os empréstimos contraídos para construir as usinas, para a operação e manutenção destas mesmas usinas, para adquirir combustíveis (no caso das usinas térmicas), e para pagar os diversos encargos e tributos relativos a suas atividades.

A transmissão faz com que a energia produzida pelas usinas chegue aos centros de consumo. Ela também viabiliza as trocas de energia entre as diferentes regiões do país, permitindo que usinas que conjunturalmente tenham maior disponibilidade (especialmente usinas hidrelétricas) produzam mais energia e compensem a eventual indisponibilidade de usinas que produzam menos energia.

As linhas e demais ativos de transmissão em alta tensão formam a chamada Rede Básica (RB) do SIN, que permite atender de forma integrada a demanda de energia do país.

Os transmissores são concessionários de serviços públicos, e têm sua remuneração estabelecida com base nos leilões que precederam as respectivas outorgas, ou então estabelecidas pela Agência Nacional de Energia Elétrica (ANEEL) no caso das concessões que chegaram a seu termo. Esta remuneração é obtida através de tarifas cobradas aos agentes que acessam as instalações de transmissão, ou seja, aos geradores de médio e grande porte, aos consumidores de grande porte e às distribuidoras.

A rede básica de transmissão é composta de instalações de transmissão cuja tensão é igual ou maior que 230 kV. As instalações com tensão abaixo de 230 kV são consideradas parte do sistema de distribuição.

A distribuição consiste em levar a energia dos “pontos de chegada” da transmissão (o termo técnico é “subestação”) até cada local de consumo, ou seja, a cada residência, indústria, comércio ou fazenda (alguns grandes consumidores, particularmente indústrias de maior porte, conectam-se diretamente à Rede Básica de transmissão).

As distribuidoras são concessionárias com monopólio da atividade de distribuição nas respectivas áreas de concessão. Eles cobram aos consumidores tarifas estabelecidas pela ANEEL, calculadas com base no custo desta atividade.

Além da distribuição propriamente dita (ou seja, da chamada atividade “de fio”), as distribuidoras têm o monopólio da comercialização de energia aos chamados “consumidores cativos”, ou seja, os consumidores de menor porte (consumidores residenciais e demais consumidores de menor porte). Para isso, elas adquirem energia dos geradores através de contratos resultantes de leilões de energia.

A receita das distribuidoras vem das tarifas cobradas aos consumidores localizados em sua área de concessão, e devem cobrir tanto as despesas relativas às atividades de distribuição propriamente dita (“fio”) como aquelas relativas à comercialização de energia (aquisição de energia de geradores, medição e cobrança), além de outras despesas (por exemplo, encargo relativo ao uso do sistema de transmissão).

Além da comercialização aos consumidores cativos, que é realizada exclusivamente pelas distribuidoras, existem outras formas de comercialização de energia, mais especificamente, a venda de energia aos chamados “consumidores livres” e “consumidores especiais”.

A comercialização de energia é atualmente realizada em dois ambientes diferentes de contratação, englobando todos os agentes do setor, e definidos como: Ambiente de Contratação Regulada (ACR) e Ambiente de Contratação Livre (ACL).

No ACR, a energia é comercializada pelas distribuidoras para o atendimento da demanda dos consumidores cativos (ou regulados), as quais devem contratar sua energia somente através de leilões públicos.^[Com exceção para distribuidoras cujo consumo é igual ou menor que 500 GWh/ano.]

No ACL, o consumidor pode optar pela compra de energia elétrica junto a qualquer fornecedor, sendo atendido em qualquer tensão e com demanda contratada mínima de 3 MW, segundo a Resolução Normativa da ANEEL n° 376/2009 e a Resolução Normativa da ANEEL n° 414/2010.^[Isto já está em mudança, e a partir de 2023, todos consumidores com carga superior ou igual a 500 kW podem participar do mercado livre de energia, via cronograma estabelecido na Portaria MME nº 465/2019.]

Salvo no caso de *holdings*, empresas só podem atuar em uma das áreas ex-comercialização.

## Geração

Alguns conceitos relacionados à produção de energia precisam ser apresentados, uma vez que as regras de funcionamento do setor adotadas pelos agentes e descritas ao longo do relatório serão baseadas neles. Neste ponto é necessário diferenciar “energia”, “potência”, “fator de capacidade” e “MW médio”.

Energia é comumente definida como a capacidade de se realizar trabalho, sendo mensurada pela unidade Joule (J). A energia elétrica é resultante de um processo de conversão da energia contida em uma fonte primária (ex: gás natural, carvão, óleo combustível, entre outros), através do uso de equipamentos de geração elétrica. No Brasil, a unidade mais utilizada para energia elétrica é o Watt-hora (Wh).

Potência, cuja unidade é Watt, é a razão entre energia produzida e a unidade básica de tempo (1 W = 1 J/s). Alternativamente pode-se definir potência como a taxa temporal de realização de trabalho. No âmbito do setor elétrico, potência corresponde à capacidade instalada de um equipamento de geração.

No entanto, é importante salientar que dois sistemas de geração com a mesma potência podem produzir diferentes quantidades de energia, dependendo da eficiência dos equipamentos, da tecnologia e dos combustíveis utilizados. O parâmetro que mede essa disparidade é o fator de capacidade, que é um percentual calculado entre a geração real e a geração máxima (teórica) daquele sistema.

O megawatt médio (MW médio) não é uma unidade de potência, mas sim de energia. Sua unidade é MWh/h, sendo obtido pela fração entre a energia produzida e o tempo de operação do sistema de geração elétrica analisado (dia, mês ou ano usualmente).

Certas fontes, como é o caso das renováveis, possuem uma atratividade maior quando comercializadas no ACL, por causa do mecanismo de contratação incentivada, criado pela Lei nº 9.648/1998 e regulamentado pela REN nº 247/2006. Essas fontes de produção têm um desconto de pelo menos 50% nas tarifas de transmissão e distribuição (TUST/TUSD), extensível aos consumidores que contratam energia oriunda destas fontes.

Adicionalmente, a regulamentação atual permite que consumidores regulado com carga superior a 500 kW, mas que não alcançam o ACL convencional podem se tornar livres, contanto que comprem energia desses geradores incentivados, o que constitui uma reserva de mercado para este tipo de gerador.^[Essa reserva está sendo reduzida por causa das modificações estabelecidas pela Portaria MME nº 465/2019, que reduzem os limites para o mercado convencional.] Esses consumidores são ditos “especiais”.

### Despacho do sistema

O despacho do sistema, isto é, as decisões sobre quais usinas acionar e como usar o sistema de transmissão, é realizado pelo ONS. O despacho é centralizado, e baseado em custos^[Atualmente, discute-se a alternativa de mudar para um despacho por preço, como é o caso dos EUA, mais especificamente na costa oeste, Áustria, Suíça, Noruega e Colômbia.], isto é, a construção da ordem de mérito de geração e, portanto, as decisões sobre como usar os recursos disponíveis (água e combustível) são feitas com base nos “reais” custos de produção dos geradores. Enquanto os custos das usinas térmicas são auditados pela ANEEL, o ONS utiliza uma cadeia de modelos computacionais de otimização estocástica para calcular o “valor da água”, que o _proxy_ do “real” custo do recurso da hidrelétrica.

O Operador se faz valer de um _software_ de otimização provido pelo Centro de Pesquisas em Energia Elétrica (CEPEL). Naturalmente, o modelo devolve uma resposta cartesiana, que talvez não leve em conta todas as variáveis do setor atualmente; então, as decisões de despacho podem incorporar instruções específicas do Comitê de Monitoramento do Setor Elétrico (CMSE) para acionar determinadas usinas térmicas e/ou realizar determinados intercâmbios regionais de energia.

### Mercado de Curto Prazo (MCP)

O despacho do ONS normalmente faz com que as usinas produzam volumes de energia diferentes daqueles que seus proprietários venderam através de contratos. Os consumidores tampouco consomem exatamente os montantes de energia que adquiriram através de contratos, especialmente em nível diário e mensal. Essas diferenças têm que ser reconciliadas, e isto é realizado todos os meses pela Câmara de Comercialização de Energia Elétrica (CCEE).

A contabilização e liquidação da CCEE, chamada Mercado de Curto Prazo (MCP), consiste em calcular, para cada gerador, a diferença entre sua produção efetiva e seus compromissos contratuais, e para cada consumidor (distribuidora ou consumidor livre), a diferença entre sua cobertura contratual e seu consumo efetivo, além de liquidar essas diferenças ao Preço de Liquidação de Diferenças (PLD). O PLD é calculado de forma horária pela CCEE para três “patamares” (carga pesada, intermediária e leve), em cada um dos quatro “submercados”, que correspondem aproximadamente (porém não exatamente) às regiões geográficas tradicionais (Sul, Sudeste/Centro-Oeste, Nordeste e Norte).

Mesmo sendo conceitualmente simples, as regras detalhadas de contabilização e liquidação ocupam centenas de páginas de fórmulas algébricas e incluem, além do mercado de curto prazo propriamente dito, a aplicação das regras básicas de segurança de suprimento, a implementação detalhada dos Contratos de Compra de Energia no Ambiente Regulado (CCEAR) e de mecanismos tais como o MRE, que é um mecanismo de compartilhamento do risco hidrológico entre as usinas hidrelétricas.

Uma característica inevitável da produção hidrelétrica é sua variabilidade em função da situação hidrológica. Isto é acentuado pela combinação da presença de grandes reservatórios, possivelmente prejudicando outras usinas a jusante; e o fato de que o sistema brasileiro tem dimensões continentais, englobando várias bacias hidrográficas com regimes hidrológicos distintos.

De fato, a operação do sistema deve ser realizada levando em conta a situação de armazenamento dos reservatórios e a conjuntura hidrológica das bacias nacionais. Caso seja dada uma prioridade de enchimento de reservatórios pelo ONS, possivelmente a situação se tornaria insustentável, tanto financeira quanto ambientalmente, aumentando o risco e afastando potenciais investidores, inviabilizando o aproveitamento do potencial hidrelétrico.

Por isso, foi concebido o Mecanismo de Realocação de Energia (MRE). Ele se baseia na predominância de geração hidrelétrica no SIN.^[De fato, atualmente, mais da metade da capacidade instalada de geração da matriz brasileira é oriunda de hidrelétricas.] A existência do MRE deriva do fato de que, por mais que as gerações individuais das usinas hidrelétricas sejam instáveis, a geração total do conjunto de todas as usinas hidroelétricas é razoavelmente estável.^[Existe certa comparação conceitual do MRE com a Teoria Moderna de Portfólio de Markowitz, diversificando o risco da insuficiência de geração entre o “portfólio” de usinas, assumindo que existe pouca covariância entre as bacias hidrográficas.]

Em termos conceituais, o MRE aloca a cada usina uma geração que corresponde a uma fração da geração total das usinas hidroelétricas, independentemente da geração física individual da usina. Esta fração é a razão da Garantia Física (GF) da usina e a soma das garantias físicas de todas as usinas participantes do MRE. Ou seja:

$$
Ger_{usina} = Ger_{total} * \frac{GF_{usina}}{GF_{total}}
$$

A título de exemplo: se uma determinada usina participante do MRE tiver garantia física de 480 MW médios, e a soma das garantias físicas de todas as usinas do MRE for 40.000 MW médios, então está usina terá direito a (480 ÷ 40.000 = 1,2%) da produção do conjunto de usinas. Assim, se em determinado período a produção total das usinas hidroelétricas for de 50.000 MWh, então a usina em questão terá direito a 1,2% de 50.000 = 600 MWh, independentemente de sua produção efetiva no período em questão. Assim, o proprietário da usina terá, para efeitos de mercado de curto prazo, direito a 600 MWh, mesmo que sua produção física no período seja de 300 MWh. Ele receberia os mesmos 600 MWh médios se a produção da usina no período for 900 MWh, ou 1.500 MWh, ou mesmo zero. Cabe ressaltar que a realocação de energia se dá apenas entre as usinas participantes do MRE.

Assim sendo, o MRE é um esquema de socialização de ônus e bônus entre as usinas hidrelétricas do SIN; entretanto, esse mecanismo não protege as usinas contra riscos “sistêmicos”, que seria quando a produção total das usinas é menor que a soma das GFs, fazendo com que as usinas tenham crédito de energia menor que suas GFs.^[Isso inclusive desencadeou a chamada “crise do GSF”, apenas recentemente resolvida.]

### Expansão da Geração

Em efeito, são duas as regras básicas que garantem a segurança de suprimento no modelo institucional do Setor Elétrico Brasileiro (SEB). São essas:

1. Toda demanda deve ser 100% coberta por contratos.
2. Todo contrato deve ter lastro físico de geração capaz de produzir o montante de energia contratada de maneira sustentável – esse lastro é chamado de Garantia Física.

De 2., sabe-se que esse lastro físico pode ser assegurado por projetos de geração própria ou por contratos de suprimento de terceiros, que por sua vez devem estar lastreados por projetos de geração.

Em efeito, então, essas regras têm uma conclusão lógica de que _“toda demanda deve ser lastreada fisicamente"_, garantindo então que a oferta de energia seja sempre maior ou igual à demanda.^[Note que energia é diferente de potência, e este é um problema recente no sistema brasileiro. Um acontecimento recente, o Leilão de Reserva de Capacidade de 2021, postergou uma solução estrutural ao problema, mas ele ainda existe.]

A cada usina no SEB é atribuído um montante de energia correspondendo a sua capacidade de produção sustentável – a Garantia Física, de unidade MW médio. Este valor é parte do contrato de concessão de hidrelétricas, assim como da autorização de outros empreendimentos.^[Equipamentos de geração que não possuem certificados de garantia física emitidos pelo MME, possuem garantia física calculada conforme a produção física no ano anterior ou a capacidade disponível.]

A metodologia para o cálculo das garantias físicas está regulamentada na Portaria MME nº 101/2016. De forma geral, ela reflete a contribuição de energia de cada usina durante os períodos secos. Todos estes valores são certificados pelo governo e publicados pelo MME para cada gerador do sistema. Para as usinas hidrelétricas, por exemplo, eles correspondem à capacidade de produção contínua durante os anos secos. Para usinas térmicas eles são dados pela capacidade disponível (descontando as taxas médias de parada forçada e programada) e ajustadas por um fator “redutor” que depende simultaneamente do custo variável unitário e geração mínima: quanto maior o custo variável unitário menor a garantia física e quanto maior a geração mínima, maior a garantia física. Já no caso de usinas eólicas, a garantia física é calculada com base na geração média esperada ao longo de vinte anos com 90% de probabilidade de ser excedida (P90 de vinte anos), conforme certificado emitido por empresa competente.

Os certificados de garantia física podem passar por processos de reajuste e/ou revisões. Os reajustes são motivados pela performance das usinas, como por exemplo a realização de paradas programadas para manutenção de termelétricas a taxas superiores aos valores padrão. Já os processos de revisão de garantia física ocorrem devido a mudanças estruturais nos equipamentos, como por exemplo uma mudança no combustível ou aumento da capacidade instalada. Existem penalidades por insuficiência de lastro relativo à energia vendida por intermédio de contratos, calculadas e processadas pela CCEE, mas de forma independente da liquidação do MCP.

No caso de hidrelétricas e termelétricas, o MME define as garantias físicas no ponto de conexão com o SIN, sendo de sua responsabilidade, antes de firmar contratos, descontar as perdas elétricas na linha de transmissão entre subestação da usina e a rede básica (linha de uso exclusivo), o consumo interno e as perdas elétricas na rede básica até o centro de gravidade, que é o ponto virtual onde a geração e o consumo de energia se igualam, tornando possível a comercialização de energia. No caso de geração não despachável, como é o caso de solar, eólica, biomassa e PCH, as garantias físicas são definidas na subestação da rede básica (ou na rede de distribuição), sendo necessário apenas descontar da garantia física as perdas na rede básica (RB).

Os leilões vigentes de contratação separam a energia em dois tipos distintos: “energia nova” e “energia “existente”. As regras do modelo comercial atual do Setor Elétrico, estabelecidas pela Lei nº 10.848/2004, definem como “novos empreendimentos de geração” aqueles que, até o início do processo licitatório, não fossem “detentores de outorga de concessão, permissão ou autorização” ou fossem parte de empreendimento existente que viesse a ser objeto de ampliação, neste caso restrito ao acréscimo de capacidade. Os demais empreendimentos eram considerados existentes. Com base nessas definições, foram estabelecidos leilões separados para a energia existente e para a energia nova. Esses leilões proporcionam à energia nova acesso exclusivo a contratos com maior duração, firmados com maior antecedência em relação à data de início de suprimento, e com preços presumivelmente mais caros.

Efetivamente, o marco regulatório, em sua versão original, estabeleceu que os leilões de energia existente deveriam oferecer contratos com início de entrega no ano subsequente ao da licitação e prazo de suprimento de no mínimo 3 e no máximo 15 anos. Já a energia nova disputaria contratos com início de entrega no 3º ou no 5º ano após a licitação e prazo de suprimento de no mínimo 15 e no máximo 35 anos.

Separação da energia nas classes “existente” e “nova” foi criada a partir da constatação de que a viabilização de projetos de novas usinas na modalidade _project finance_ exigia a garantia de receitas estáveis pelo menos durante todo o prazo do financiamento (inicialmente prazos de 12 a 15 anos, que posteriormente foram aumentados). Ocorre que, no modelo comercial vigente, a única fonte de receita estável para um projeto de geração seria um contrato de suprimento de energia, já que os preços do mercado de curto prazo são por natureza voláteis em nosso sistema (além de estarem sujeitos a variações por mudanças regulatórias), e as receitas decorrentes de encargos são em geral eventuais, e completamente incompatíveis com os custos de investimento e operação de empreendimentos de geração.

No caso de empreendimentos termelétricos movidos a combustíveis fósseis, a garantia física está condicionada à apresentação de contratos de suprimento firme de combustível. Caso as usinas não possuam contratos de suprimento de combustível, ou caso seja comprovado que não há disponibilidade firme do insumo, a garantia física pode ser reduzida ou mesmo zerada. Nos contratos de energia nova, a falta de combustível não justifica indisponibilidade do gerador. Além disso, se a razão da indisponibilidade de uma usina for falha no suprimento de combustível líquido, o gerador incorre em penalidade no valor de 10% do custo variável unitário, de acordo com a Resolução Normativa ANEEL no 827 de agosto de 2018.^[O gerador incorre nesta penalidade somente se a soma das indisponibilidades for maior que 10% da potência despachada em um determinado mês. Para as usinas com combustíveis sólidos a penalidade varia entre 0% e 30% do CVU dependendo do montante indisponível devido à falta de combustível.]

Todas as novas unidades geradoras, ou aquelas que alterarem seu combustível principal, devem solicitar à ANEEL a liberação para início de operação em teste, comercial ou para estar apta a operação comercial (quando a usina está impossibilitada de disponibilizar potência ao SIN em razão de atraso ou restrição no sistema de transmissão ou distribuição). Estão liberados deste procedimento os agentes detentores de registro ou autorização, que não tenham sua energia elétrica contabilizada na CCEE ou comprometida com concessionária ou permissionária de distribuição de energia elétrica.

A expansão de nova capacidade fora do ambiente regulado tem ocorrido principalmente através de:

- **Geradores que participam dos leilões regulados e vendem energia remanescente para o ACL.** Este é o caso por exemplo dos grandes projetos hidrelétricos do Rio Madeira e da UHE Belo Monte, que venderam 70% da sua energia através de contratos no ambiente regulado e comercializaram o restante no mercado livre. Esta estratégia também foi utilizada por alguns empreendimentos eólicos nos leilões de energia nova de 2018, que chegaram a vender apenas 50% da energia no ACR;
- **Empreendimentos de energia incentivada,** que são viabilizados pelo desconto na tarifa fio dos consumidores livres que contratam esta energia. Um exemplo deste tipo de estratégia foi o leilão de energia incentivada organizado pela Cemig para a compra de ativos de geração eólica e solar, oferecendo contratos similares aos oferecidos nos leilões regulados. O comercializador da estatal mineira seria a responsável por vender a energia para os consumidores finais ao longo do período de contratação, que usufruirão do benefício do desconto na tarifa fio; e
- **Empreendimentos construídos para autoprodução de energia,** onde os consumidores possuem uma série de benefícios relacionados principalmente ao não pagamento de alguns encargos setoriais. Um exemplo de modelo comercial é a transação entre a empresa geradora Casa dos Ventos, que é responsável por construir e operar parques eólicos que seriam posteriormente arrendados para a consumidora Vale, permitindo auferir os benefícios da autoprodução de energia.

Mais recentemente a expansão fora do ambiente regulado tem ocorrido também através da micro e minigeração distribuída. Este modelo de negócios é beneficiado principalmente pelo mecanismo de net metering instituído pela Resolução Normativa ANEEL no 482/2012 e pela redução do pagamento de encargos setoriais, impostos e tarifa de distribuição dos consumidores de baixa tensão causada pelo modelo de tarifação apenas pelo consumo da energia (tarifa volumétrica ou monômia).^[A tarifação monômia do Grupo B faz com que consumidores que instalam micro e minigeração distribuída e reduzem seu consumo mensal faturado de energia evitem o pagamento dos custos fixos para o fornecimento de energia elétrica. Esse pagamento atualmente é feito através da cobrança do custo de disponibilidade, que é o consumo mínimo que cada consumidor de baixa tensão deve pagar de acordo com seu tipo de ligação (monofásica, bifásica e trifásica), no entanto, essa forma de cobrança tem sido contestada por não representar o custo que a distribuidora incorre para disponibilizar o sistema aos consumidores. No caso dos consumidores conectados em alta tensão (Grupo A) há cobrança por energia (R\$/MWh) e demanda (R\$/kWmês), fazendo com que consumidores continuem pagando pela utilização da rede de distribuição.]

Finalmente, o Governo pode ainda realizar leilões especiais para contratar energia de reserva. Esses leilões são totalmente definidos pelo governo – desenho, tipo de energia a ser contratada, demanda do leilão, etc. A finalidade da energia de reserva é aumentar a segurança de suprimento do sistema com relação ao critério utilizado para o cálculo de garantia física dos empreendimentos. Afinal, se todos os consumidores devem estar 100% contratados e todos os contratos são respaldados por garantia física, o mecanismo de contratação dos leilões regulados ou as negociações bilaterais no mercado livre deveriam ser suficientes para entregar a segurança de suprimento embutida nos certificados de garantia física. Como razões para a necessidade de contratação de energia de reserva é possível citar: 

- Mudança no critério de segurança de suprimento sem estar refletida nos reajustes ou revisões de garantia física; 
- Imperfeições no processo de reajuste/revisão de garantia física, como por exemplo não considerar a variação do custo variável unitário das termelétricas; 
- Descompasso entre os dados dos modelos computacionais utilizados para o cálculo da garantia física e os dados reais do sistema (e.g. série de vazões, eficiência da usinas, dados de irrigação, etc); e 
- Proteção contra atrasos sistêmicos dos empreendimentos de geração.

## Transmissão

O sistema de transmissão brasileiro possui mais de 145 mil km de linhas em operação até o final de 2018, com tensões iguais ou maiores que 230 kV. O sistema de transmissão brasileiro tem crescido significativamente nos últimos tempos, com taxas que excedem até mesmo o crescimento da demanda de energia. As razões desse fato estão relacionadas a importantes fatores da expansão do sistema de transmissão, tais como expansão do parque gerador longe do centro de carga, reforço na confiabilidade do sistema e atendimento à demanda de energia.^[Enquanto a média anual de crescimento da demanda de energia no Brasil estava próxima de 2,8% a.a. no período entre 2004 e 2018 a média do crescimento do tamanho total do sistema de transmissão foi aproximadamente de 4,0% a.a. no mesmo período.]

O principal mecanismo de implementação da expansão do sistema de transmissão usado atualmente no Brasil, que corresponde a seleção de empresas de transmissão através de leilões de concessões de transmissão, permitiu uma atração significativa do capital privado para o setor desde o começo dos anos 2000. Contudo, o papel do setor público no segmento de transmissão brasileiro ainda é marcante. 

Além do projeto de Itaipu Binacional, que envolve Brasil e Paraguai, existem 3 outras interconexões internacionais com o SIN: Argentina, Uruguai e Venezuela:

1. **Brasil-Argentina.** São duas as interconexões elétricas com a Argentina, ambas feitas através de conversores de frequência de 50/60 Hz, do tipo _“back-to-back”_. A primeira é a estação conversora Uruguaiana, de propriedade da Eletrosul, consistindo em um único conversor de frequência de 50/60 Hz, com capacidade de 50 MW, conectando Paso de Los Libres na Argentina na subestação de Uruguaiana localizada no estado do Rio Grande do Sul; e a segunda é a estação conversora Garabi 1 e Garabi 2, de propriedade da CIEN, cada uma consistindo em dois conversores de frequência de 50/60 Hz de capacidade de 550 MW cada. O ponto de entrega do conversor Garabi 1 é localizado na subestação Santo  ngelo e o ponto do conversor Garabi 2 na subestação Itá (SE Itá).
2. **Brasil-Uruguai.** Em 2014, o Brasil tinha uma única conexão elétrica com o Uruguai feita por um conversor de frequência de 50/60 Hz, _“back-to-back”_, de 70 MW de capacidade, de propriedade da UTE (uma empresa uruguaia), localizada em Rivera (Uruguai) e conectada no lado brasileiro por uma linha de transmissão de 230/150 kV na subestação de Santana do Livramento. Ao longo de 2015, esta interconexão foi reforçada através de um conversor de frequência de 50/60 Hz de 500 MW, localizada em Melo (Uruguai), construída pela Eletrosul e UTE, e conectada no lado brasileiro por uma linha de transmissão de 525 kV na subestação de Candiota.
3. **Brasil-Venezuela.** Finalmente, esta interconexão é realizada através de um sistema de transmissão de 230/400 kV, com 780 km, conectando a subestação de Boa Vista no Brasil com a subestação de Macagua na Venezuela. Apesar da capacidade do sistema ser de 200 MW, devido ao déficit de potência reativa do lado da Venezuela, mesmo após o início da operação do compensador de estado sólido de 230 kV da SE Boa Vista, não é possível importar mais que 150 MW.

Efetivamente, uma empresa pode entrar como concessionária no segmento brasileiro de transmissão pode ocorrer através de duas formas: participação em leilões de novas concessões, organizados pela ANEEL; e aquisição de ações ou ativos de empresas existentes. A existência de somente estas duas alternativas de entrada no mercado decorre devido à regulação aplicável ao segmento da transmissão que determina que todas as novas concessões de transmissão devem ser leiloadas. Será visto mais adiante que reforços e melhorias nas concessões existentes podem ser autorizados diretamente pelo regulador, mas concessões de ativos em estágio inicial devem necessariamente ser leiloadas. De maneira geral, não existe um modelo comercial da transmissão, no mercado brasileiro, que permita a um empreendedor a implementação e operação de novos ativos por sua própria conta e risco.^[Entretanto, existem algumas situações especiais em que a ANEEL tem o poder discricionário de transferir a concessão de uma instalação de transmissão de uma empresa para outra, em caráter emergencial.]

Em um leilão de transmissão, a concessão de novas instalações de transmissão é disputada através do valor da Receita Anual Permitida – RAP. O vencedor do leilão é aquele que oferece menor desconto nessa receita, e tem sua RAP definida no momento em que as concessões são leiloadas, conforme o modelo _revenue cap_. Esse é o modelo vigente de remuneração de preços desde 1996, com a publicação da Lei nº 9.427/1996; antes, era feita uma remuneração via _cost of service_.^[Os modelos de remuneração _price cap_ – o atualmente usado por distribuidoras – e _revenue cap_ são similares, entretanto diferem no seu uso. A principal diferença está no fato da regulação por _revenue cap_ ter foco na regulação da receita total da empresa regulada, enquanto o _price cap_ tem como objetivo central a regulação do preço máximo a ser praticado para o fornecimento de energia elétrica. Woolf e Michals [-@woolf1995] e Jamison [-@jamison2007] afirmam que a diferença fundamental dos dois métodos reside no fato de no _price cap_ o nível de receita mudar para refletir alterações nos níveis de venda do produto, enquanto no _revenue cap_ isso não ocorre.]

### Riscos associados à transmissão

Uma parte significativa dos riscos associados à atividade de transmissão está relacionada com a fase de implantação das instalações de transmissão - ou seja, a fase que envolve as atividades de licenciamento ambiental, aquisição de terrenos, engenharia, construção e instalação das instalações de transmissão.

Os eventos que ocorrem nesta fase podem levar a um aumento das despesas de capital necessárias para a implementação de projetos e atrasos no cronograma de comissionamento - com impactos significativos sobre a situação financeira das concessionárias. Os atrasos nos cronogramas de implantação de projetos resultam em diferentes consequências para os investidores. Além do impedimento na participação em leilões futuros, atrasos no cronograma de implementação causam perda de receita (que são apenas recebidas após o comissionamento de instalações), possibilidade de execução de garantias financeiras, descontos na RAP que serão recebidos após o início da operação comercial das instalações, e penalidades identificadas em regulamentos específicos.

Os incentivos ao cumprimento do cronograma de implantação das instalações de transmissão já existem antes de 2012, mas foram reforçados pela ANEEL em 2016. Algumas das medidas tomadas desde essa data são a preclusão acima mencionada de "empresas atrasadas" nos leilões de transmissão e a melhoria das regras de execução da garantia de fiel cumprimento depositada pelas empresas e executada em caso de não cumprimento das cláusulas contratuais.

Mesmo que o aumento de punições seja uma medida legítima, seu efeito final aumentou substancialmente a percepção de risco associado à implantação de instalações de transmissão, o que contribui para o aumento do número de lotes vazios nos leilões de transmissão. Parte desse aumento está relacionado a restrições de participação de "empresas com baixo desempenho" nos leilões, outra parte está relacionada à recusa de novas empresas ou àqueles que não apresentaram atrasos em projetos passados, de se exporem ao risco de implantação de instalações. Isso ocorre também porque não houve medidas suficientes até o final de 2014 para contribuir com a viabilidade dos cronogramas de implantação das instalações, em particular no que diz respeito à viabilidade do processo de emissão de licenciamento ambiental. Na verdade, várias instituições do setor - e até mesmo o Senado - reconheceram que melhorias são necessárias neste assunto.

No entanto, é importante notar que os riscos associados às concessões de transmissão não são apenas aqueles relacionados com atrasos na fase de implantação dos projetos. Um componente de risco importante refere-se ao risco regulatório.

Conforme verificado em outros segmentos do setor elétrico, o risco regulatório percebido pelos potenciais investidores no segmento de transmissão aumentou significativamente desde 2012, por fatores que incluem o atraso na definição do mecanismo de pagamento e valores das indenizações às transmissoras que detinham ativos existentes em 2000 e que tiveram suas concessões renovadas no final do ano de 2012 pela emblemática Medida Provisória nº 579/2012, futuramente convertida em Lei nº 12.783/2013.^[Através de cálculos da ANEEL, essa Medida provocou, desde então, um aumento superior a R\$ 200 bilhões no setor, provocando um aumento **real** das tarifas, de 2013 a 2018, de 20,4%. Os principais itens deste aumento foram o risco hidrológico de geradores, os empréstimos realizados à CDE, indenizações a geradoras e transmissoras, bonificações de usinas cotistas, assim como a não-realização de um leilão de energia nova (LEN) em 2014.] O atraso na execução do pagamento destas compensações não só agravou a percepção do risco regulatório, mas também impactou a capitalização das empresas afetadas e sua capacidade de investimento no curto prazo uma vez que no momento da renovação das concessões, os referidos ativos foram artificialmente amortizados e as receitas anuais das transmissoras reduzidas.

A situação descrita, em que companhias do segmento de transmissão tiveram suas receitas fortemente impactadas em virtude de uma decisão discricionária do poder concedente, evidencia a dificuldade de gerenciamento e mitigação do risco regulatório. O aumento na percepção de risco regulatório pode ter sido grande o suficiente para representar uma barreira quase "binária" para participação de empresas na competição por novas concessões. Quando o risco atinge um certo limiar, o investidor exige um prêmio de risco tão alto para investir em ativos de transmissão que, na verdade, o aumento da RAP máxima torna-se inofensivo. Além disso, os riscos muito elevados tendem a assustar os investidores que são mais prudentes e realistas em suas avaliações, na medida em que procuram preservar a classificação de crédito de suas companhias, evitando alocar em seu portfólio ativos muito arriscados.

Um risco final relevante refere-se à disponibilidade de capital. Este é um fator muito importante, dada a natureza intensiva de capital da atividade de transmissão.

A atração de capital estrangeiro para o segmento de transmissão é prejudicada pelo momento macroeconômico brasileiro, sendo dependente de fatores como taxa de juros, fatores inflacionários e taxa de câmbio; no que tange ao financiamento através de capital doméstico, este também está sujeito à macroeconomia do Brasil, impactando principalmente o BNDES do Brasil, historicamente o principal financiador da expansão da transmissão. Uma das mudanças mais importantes nas condições de financiamento do BNDES é a mudança da participação máxima do banco em itens financiáveis. Algumas instituições da indústria apontaram que as debêntures de infraestrutura poderiam ter um papel relevante no segmento de transmissão. Essas debêntures foram introduzidas pela Lei nº 12.431/2011, a fim de aumentar a participação do mercado de capitais no mix de empresas e estabelecer incentivos fiscais para suas _“holdings”_. No entanto, a contribuição média desses instrumentos na estrutura de capital do vetor ainda é limitada.

A estimativa da rentabilidade dos projetos de transmissão depende em geral de diversos parâmetros que inicialmente são definidos regulatoriamente para o cálculo da Receita Anual Permitida máxima para cada lote a ser licitado no leilão. Os estudos de engenharia técnica e econômica que as empresas que desejam participar dos leilões de transmissão realizam, resultam na alteração desses parâmetros com o objetivo de aumentar a competitividade dos competidores. Os parâmetros definidos regulatoriamente para cada lote a ser licitado são listados abaixo:

1. Principais características técnicas do lote de transmissão;
2. Custos de investimento e operação; 
3. Taxa de depreciação dos ativos;
4. Data de entrada em operação;
5. Estrutura de capital; e
6. Tipos de financiamento.

Por mais que esses riscos apresentem um desafio a investidores, o setor de transmissão brasileiro como um todo é bem regulado, o que contribui de certa forma para a atração de investidores, sendo este considerado o segmento menos arriscado do setor elétrico.

### Modelo regulatório, institucional e contratual

O modelo regulatório de transmissão é baseado em concessões públicas, pelo fato principal da atividade constituir um monopólio natural. Um monopólio natural é um monopólio em uma indústria na qual altos custos de infraestrutura e outras barreiras à entrada em relação ao tamanho do mercado dão ao maior fornecedor em uma indústria, frequentemente o primeiro fornecedor em um mercado, uma vantagem esmagadora sobre concorrentes potenciais.^[Isso ocorre frequentemente em indústrias em que predominam os custos capitais, criando economias de escala grandes em relação ao tamanho do mercado; exemplos incluem empresas de serviços públicos como serviços de água e eletricidade.]

O modelo aplica-se às concessões que foram objeto de licitação competitiva. Na sua forma mais simples, consiste em:

1. Estabelecimento de um valor de RAP mediante licitação (ou seja, a concessão é concedida ao candidato que se propõe a construir, manter e operar as instalações correspondentes com o menor valor anual de compensação);
2. Uma vez que as instalações estão em operação comercial, a concessionária receberá a remuneração anual resultante da licitação até o final do período de concessão, com direitos de indexação periódica (anual), de acordo com o índice estabelecido no próprio contrato de concessão.

Quando este modelo foi implementado, ele realmente tinha essa forma: a Receita Anual Permitida (RAP) estabelecida no processo de licitação não estava sujeita a revisões, era indexada apenas anualmente,^[Atualmente, o índice mais utilizado é o IPCA, entretanto antigamente era o IGP-M.] porém o contrato também estabelecia que o valor da RAP seria reduzido pela metade a partir do 16º ano de operação comercial.
Esta aplicação "quase pura" do modelo _“revenue cap”_ também teve adaptações:

- A receita da companhia de transmissão era sujeita a uma redução de até 12,5% dependendo do desempenho das instalações. Esta parcela de ajuste é chamada de parcela variável;
- No caso de extensões e reforços, as receitas eram estabelecidas pela ANEEL e eram sujeitas a processos de revisão.

Em 2006, no entanto, o TCU ordenou à ANEEL que a RAP das concessões licitadas deveria ser revisada periodicamente. Desde então, a ANEEL estabeleceu que as revisões ocorreriam a cada cinco anos. A regra de revisão afeta apenas a parcela do investimento entendida como "custo da dívida" e os custos relacionados à operação e manutenção, ambos calculados para as concessões existentes de acordo com os parâmetros estabelecidos pela ANEEL. No caso de novas concessões, os parâmetros já estão incluídos no Documento de Licitação e no Contrato de Concessão. Desta forma, o regime de preços foi preservado.

Nesta seção, discutimos como os custos associados à atividade de transmissão são alocados entre os usuários do sistema de transmissão e como as receitas necessárias para cobrir esses custos são recuperadas. Existem duas categorias básicas de custos associados à atividade de transmissão^[Além dessas duas categorias, também há os custos das reduções de carga devido às limitações da capacidade de transmissão - por exemplo, os custos de interrupção das atividades produtivas incorridas pelos consumidores quando ocorrem apagões. Tais custos afetam diretamente os consumidores.]:

1. Custos relacionados à provisão de infraestrutura de transmissão.
2. Custos operacionais adicionais do sistema de geração causados ​​por fenômenos relacionados à rede de transmissão.

Os custos da categoria (1) referem-se basicamente aos requisitos de receita - RAP - das empresas de transmissão, responsáveis ​​pela implantação e operação das instalações de transmissão, enquanto os custos da categoria (2) referem-se basicamente a custos causados ​​por fenômenos de transmissão, mas incorrerão em custos adicionais da operação do sistema de geração: (i) custos decorrentes da necessidade de re-despachar o sistema de geração devido ao congestionamento de transmissão; (ii) custos das perdas de energia no sistema de transmissão, o que implica a necessidade de gerar mais energia do que a necessária para atender ao consumo de energia.

A alocação dos custos de infraestrutura de transmissão é feita através do procedimento de cálculo e homologação da Tarifa de Uso do Sistema de Transmissão (TUST), enquanto a recuperação desses custos é feita através dos Encargos de Uso do Sistema de Transmissão (EUST) paga pelos usuários devido ao uso do sistema de transmissão. O valor mensal do EUST é dado pelo produto da TUST, definido em R\$/(kW·mês), pelo Montante de Uso do Sistema de Transmissão (MUST), expresso em kW.^[Esse montante corresponde, basicamente, à declaração da potência máxima injetada pelo usuário do sistema de transmissão.] O EUST também pode incluir montantes adicionais, referentes a penalidades por excessos do MUST contratados ou compensações por sobrecargas de instalações e equipamentos da concessionária.

Cada concessão está associada a um conjunto de instalações de transmissão, conforme definido no respectivo contrato de concessão e é de responsabilidade da concessionária construir, operar e manter as instalações correspondentes. A operação é realizada sob a coordenação do ONS, que é responsável pelas decisões sobre o despacho de geração e operação do sistema. Desta forma, a concessionária opera suas instalações de acordo com as instruções do ONS e não tem autonomia para decidir os fluxos que irão percorrer suas instalações.

As concessionárias de transmissão têm direito a remuneração em troca de serviços prestados à rede, com as concessões sendo de duração limitada e não podendo, em termos gerais, ser estendidas, com os principais tipos sendo:

- **Concessões “antigas”.** Estas são as concessões de transmissão que já existiam em 1995, quando entrou em vigor a Lei nº 9.074/1995. Essas concessões inicialmente tiveram seus prazos prorrogados por vinte anos (na maioria dos casos, até 2015), e depois foram renovados por mais trinta anos. Estritamente, as renovações foram feitas à escolha das concessionárias, mas, na prática, as condições oferecidas para a renovação da concessão no momento em que foi proposta foram aceitas por todas as concessionárias que tinham direito à opção de renovação. No caso dessas concessões, a remuneração inicial foi estabelecida pela ANEEL em 1995 e, desde então, foi submetida a reajustes anuais e revisões periódicas. As tarifas e os contratos de concessão foram revisados ​​por ocasião da renovação da concessão em 2012.
- **Concessões resultantes de leilões.** Estas são as concessões de transmissão que foram leiloadas a partir da validade da Lei nº 9.074/1995. Nesse caso, a remuneração inicial foi estabelecida pelo próprio processo de licitação, sujeita a reajustes anuais e revisões periódicas. As revisões foram introduzidas a partir de 2007 pelo requerimento do TCU e, na prática, são em geral suaves, afetando apenas uma parte das receitas da concessionária.

O conjunto de relações contratuais que sustenta o modelo regulatório envolve:

- A relação entre cada concessionária (companhia de transmissão) e a Autoridade de Concessão (MME), que é regulada pelo respectivo Contrato de concessão;
- A relação entre cada agente de transmissão e o ONS, que é regulado pela Contrato de prestação de serviços de transmissão (CPST);
- A relação entre cada usuário do sistema de transmissão (gerador, distribuidor ou consumidor que se conecta diretamente à Rede Básica) e o ONS, que é regulado pelo Contrato para o uso do sistema de transmissão (CUST); e
- A relação entre cada agente de transmissão e cada usuário do serviço de transmissão que se conecta através de suas instalações, que é regulado pelo Contrato de Conexão do Sistema de Transmissão (CCT).

Além desses contratos e acordos, existem os CCI (Contratos de Compartilhamento de Instalações), que permitem a partilha de certas instalações por dois ou mais agentes, e o CCG (Contrato de Constituição de Garantia), que garante o pagamento da TUST (Tarifa do Uso do Sistema de Transmissão) pelos usuários do sistema de transmissão.

## Distribuição

No Brasil, o segmento de distribuição de energia é aquele responsável por entregar energia elétrica ao usuário final. As distribuidoras exercem a atividade de disponibilização de infraestrutura de redes elétricas de distribuição (por vezes chamado de serviço _fio_) e a atividade de comercialização de energia a consumidores cativos.

A distribuição de energia em solo brasileiro é um serviço público exercido mediante concessão (ou permissão) do Estado e regulado pela ANEEL. A característica básica do modelo contratual dessas concessões é a regulação por incentivos no modelo de preços máximos (_price cap_).^[Neste regime, o regulador estabelece um conjunto de tarifas a serem cobradas pelo serviço durante um período pré-determinado. Durante este prazo, essas tarifas são _reajustadas_ para capturar os índices da inflação e para repassar custos não administráveis pela distribuidora (contratação de energia, custos de conexão e uso da transmissão e os encargos setoriais). Muitas vezes, o regulador também autoriza tarifas que evoluem segundo uma “trajetória” eficiente durante este período – normalmente uma trajetória decrescente, com o regulador assumindo que a distribuidora pode aumentar sua eficiência produtiva durante o período, e incentivando tal comportamento através de tarifas decrescentes. Além disso, o regulador implementa periodicamente um processo de _revisão_ de tarifa, ao fim de cada período tarifário, para restabelecer o equilíbrio econômico da distribuidora e ajustar a remuneração do capital às condições atuais.] 

O ponto importante é que as tarifas são desacopladas da evolução dos custos reais da empresa. Elas basicamente representam uma referência estabelecida pelo regulador com base em premissas sobre o que seria um comportamento eficiente da distribuidora. Dessa forma, se a concessionária consegue estabelecer um patamar de custos mais eficiente que a permita incorrer em despesas inferiores às embutidas na tarifa, ela pode capturar ganhos durante o prazo de vigência das tarifas. O consumidor também se beneficia na medida em que, no ato da revisão tarifária periódica – que ocorre no Brasil, em média, a cada 4 anos^[Os contratos de concessão firmados após a Lei nº 12.783/2013 e Decreto nº 8.461/2015 vêm uniformizando esse período entre revisões em cinco anos.] – os ganhos de eficiência são repassados ao consumidor.

Apesar disso, uma crítica clássica ao regime _price cap_ é que esse mesmo incentivo na verdade encorajaria as companhias a degradar a qualidade de seus serviços em um esforço para diminuir custos. Assim, são necessários outros mecanismos de incentivo ou de fiscalização para impedir esse potencial problema.^[Estes podem ser vistos com maior detalhe nos Procedimentos de Distribuição de Energia Elétrica no Sistema Elétrico Nacional – PRODIST da ANEEL.]

Da descrição do regime _price cap_ fica claro que o seu principal objetivo é promover um ambiente de incentivos para que a empresa regulada busque ser mais eficiente. Essa é a razão pela qual esse regime também é conhecido como regime de “regulação por incentivos”. Entretanto, para garantir que os benefícios desse regime serão absorvidos pelos consumidores é necessário que o arcabouço regulatório e institucional seja robusto de maneira a dar segurança às empresas de que as condições estabelecidas nos contratos de concessão serão cumpridas.

Uma distribuidora de energia no Brasil presta, sob regime de exclusividade em sua área de concessão, dois serviços aos consumidores conectados em sua rede:

1. Disponibilização da estrutura de redes, sendo que não há regime de exclusividade desse serviço nos casos onde a ANEEL detecta a atuação de cooperativas de eletrificação rural; e
2. Comercialização de energia para os consumidores conectados à sua rede, sendo que não há regime de exclusividade no atendimento aos consumidores que, por força de Lei, tenham direito de adquirir energia elétrica de terceiros (os chamados consumidores livres).

Dentro do modelo contratual que se aplica ao segmento, os principais contratos relacionados à prestação de serviços de disponibilização de estrutura de redes e de comercialização de energia são: o Contrato de Concessão, o Contrato de Conexão às Instalações de Distribuição, o Contrato de Uso do Sistema de Distribuição, o Contrato de Compra de Energia Regulada; e o Contrato de Adesão.

### Expansão do sistema de distribuição

Investimentos no segmento de distribuição de energia são periódicos e condicionados principalmente às necessidades de manutenção e reforço de rede. Os principais condicionantes para esses investimentos são as políticas de revisão tarifária aplicadas pela ANEEL, as condições de financiamento e os custos operacionais do segmento.

A expansão da rede de distribuição envolve, assim como as atividades de expansão de outros segmentos do setor elétrico, as etapas de _planejamento_ da expansão, com a identificação de quais as obras a serem executadas e qual o seu cronograma pretendido de entrada em operação; e _implementação_ das obras, que se refere à execução dos investimentos e à construção dos ativos físicos.

No segmento da distribuição de energia elétrica, a distribuidora é basicamente responsável pelas duas etapas. Podem ser identificadas, como resultado do processo de planejamento centralizado da expansão do sistema de transmissão, obras em sistemas de distribuição em 138 kV (ou níveis de tensão similares) que são necessárias para a adequada operação da Rede Básica de transmissão ou da rede de operação do ONS – e, nestes casos, a implantação destes ativos pelas distribuidoras pode ser requerida pelo ONS ou pela EPE.

No entanto, o mecanismo acima indicado tipicamente não responde pela parcela mais significativa dos investimentos em expansão das redes pelas distribuidoras. As próprias concessionárias de distribuição são responsáveis pelo planejamento da expansão de suas redes, um tratamento fundamentalmente distinto daquele verificado para o sistema de transmissão, em que uma instituição governamental ou para-governamental (EPE ou ONS) é responsável pelo planejamento determinativo da expansão da rede. A lógica distinta daquela aplicada ao planejamento da expansão do sistema de transmissão se justifica por algumas características técnico-econômicas da atividade de distribuição, dentre as quais se destacam:

1. **A maior granularidade dos investimentos.** A rede de distribuição tem, via de regra, um número de ativos bastante superior àquele da rede de transmissão, e tais ativos tem um porte bastante inferior àquele da rede de transmissão. Isto dificulta o planejamento centralizado por parte de uma instituição governamental a nível nacional, fazendo com que a delegação das decisões de investimentos à distribuidora se configure como decisão percebida como mais eficiente.
2. **Assimetria de informações e necessidade de inserção em sistema de incentivos integrado.** A distribuidora é o agente melhor posicionado para adquirir informações relevantes ao planejamento da expansão da sua rede, devido a fatores que incluem tanto a já mencionada maior granularidade dos ativos e ao fato que a distribuidora tem acesso direto a dados essenciais para a previsão do comportamento da demanda pela infraestrutura de redes na sua área de concessão e, portanto, para o planejamento da expansão das redes.^[O comportamento da demanda pode variar enormemente entre áreas de concessão, especialmente em um país com dimensões continentais e com grande diversidade socioeconômica, demográfica e climática como o Brasil.] Isto contribui para a percepção de que seria ineficiente atribuir as decisões de expansão a uma instituição a nível nacional. Além disso, as distribuidoras estão mais bem posicionadas para avaliar as relações de compromisso entre decisões capital-intensivas, que envolvem a construção de novas instalações, e decisões intensivas em custos operacionais. A necessidade de considerar um sistema de incentivos que busque equilibrar otimamente as duas alternativas para garantir o atendimento adequado aos consumidores torna importante atribuir ao mesmo agente responsável por tomar decisões de _operação_ da rede (a distribuidora) as decisões de _expansão_ da rede.

É tarefa do quadro legal, contratual e regulatório aplicável ao segmento de distribuição estabelecer uma estrutura de incentivos que leve, idealmente, ao equilíbrio dos requisitos de _suficiência_ de investimentos para garantir o atendimento às demandas da sociedade; e _eficiência_ das decisões de investimento em – e operação de – redes elétricas, de maneira a não onerar desnecessariamente a sociedade no que toca a remuneração regulada do agente que exerce a atividade de monopólio natural de disponibilização de infraestrutura de redes.

Em geral, o regulador determina um valor regulatório do Custo de Capital Ponderado (WACC) que não tem como objetivo capturar _exatamente_ os custos de captação de capital da distribuidora, mas sim estabelecer uma referência eficiente dos custos de capital. Este se aplica aos custos de equipamentos e instalações: não se busca capturar exatamente os valores atingidos pelas empresas, mas estabelecer referências eficientes para estes valores. O desacoplamento entre o valor regulatório destes parâmetros o custo efetivo incorrido pela concessionária fornece incentivos para que a empresa busque a eficiência nas suas atividades de implantação da expansão, já que os acionistas vão capturar a diferença entre os valores de receitas autorizadas com base nos valores regulatórios e os custos reais incorridos. Este é um mecanismo de remuneração a acionistas, mas a ANEEL define no PRODIST certos incentivos que estão intimamente relacionados à definição das Receitas Requeridas pelas concessionárias de distribuição, que são determinadas como a soma de duas parcelas:

- **Parcela A.** A Parcela A visa recuperar custos de aquisição de energia elétrica, os custos incorridos pela distribuidora com a contratação da conexão e do uso do sistema de transmissão, e os custos de encargos setoriais. Esta parcela está diretamente ligada ao repasse dos custos de políticas de governo (encargos setoriais) e da disponibilização de infraestrutura de redes de transmissão (a cargo das transmissoras de energia), mas principalmente, sob o ponto de vista da distribuidora, com a atividade de aquisição de energia para o suprimento de consumidores regulados. Este último ponto é afetado pelos incentivos para a redução de perdas elétricas e quanto à contratação de energia. Esta parcela também é chamada de “custos não-gerenciáveis”.
- **Parcela B.** A Parcela B é aquela que visa a recuperar os valores reconhecidos pelo regulador dos custos de administração, operação e manutenção da distribuidora e também a remuneração e recuperação do capital investido nas de redes de distribuição. Além disto, esta parcela é afetada por incentivos de qualidade e de produtividade a que as distribuidoras são expostas. Esta parcela também é chamada de “custos gerenciáveis”.

### As Tarifas de Fornecimento

A Tarifa de Fornecimento (TF) é o valor cobrado pelas distribuidoras, de seus consumidores, pela prestação de dois serviços:

1. **”Fio”.** Disponibilização da infraestrutura de transporte que leva a energia do ponto de conexão com a rede de transmissão, até o ponto de consumo; e
2. **Comercialização de energia.** Aquisição e revenda, aos seus consumidores, da energia que será consumida por eles.

Custos de políticas de governo e custos sistêmicos sob forma de encargos setoriais também estão inclusos na TF.

A ANEEL, entretanto, tem outra forma de alocar os custos da Parcela A e B, através das tarifas de fornecimento homologadas:

- **Tarifa de Energia (TE),** componente cuja principal despesa está associada aos custos com compra de energia pela distribuidora, e que, portanto, deve ser paga pelos consumidores que adquirem energia da distribuidora – consumidores cativos, ou regulados; e
- **Tarifa de Uso dos Sistemas de Distribuição (TUSD),** componente cuja principal despesa está associada ao custo da infraestrutura de transporte da energia e que, portanto, deve ser paga por todos os consumidores que usam a rede da distribuidora, sejam eles cativos ou livres.

Dos custos que compreendem a Tarifa de Energia, o mais importante, e ao mesmo tempo o que carrega o maior nível de incerteza é o custo com a compra de energia. Essa rubrica agrega o custo de todos os contratos de compra de energia firmados pela distribuidora para atendimento ao seu mercado.

A ANEEL considera os custos de contratos de energia adquiridos pela distribuidora visando o atendimento à carga regulatória, com uma tolerância de 5% de excesso de contratos frente a essa carga e com algumas possíveis glosas^[Montante de energia adquirida para cobrir as perdas elétricas ocorridas acima do patamar regulatório, obtido pela diferença entre a carga real e o requisito regulatório.] em função dos mecanismos de incentivo à eficiência na contratação.

Um item importante do processo de apuração dos custos de compra de energia é a precificação de contratos cujo custo real não é conhecido _ex ante_, ou seja, não é conhecido no momento do processo tarifário. Por não dispor da informação do custo real dos contratos no momento do processo tarifário, para fins da composição final dos custos com compra de energia, a ANEEL realiza uma projeção dos custos dos contratos por disponibilidade, do risco hidrológico das cotas de garantia física e dos contratos repactuados, e da taxa de câmbio para realizar a conversão do custo de Itaipu para R\$.

Além dos custos de compra de energia, são incluídos ainda outros componentes de custos, como encargos, o P&D da ANEEL, as perdas da Rede Básica, os custos de transmissão de Itaipu, e componentes financeiros da Parcela A .

Finalmente, a tarifa de fornecimento também é composta pela Tarifa de Uso do Sistema de Distribuição (TUSD), sendo esta composta por cinco grupos de custo, associados a: perdas elétricas, encargos setoriais, custos de transmissão, custos de distribuição, e componentes financeiros.

Uma vez que a ANEEL define os valores da receita requerida que a distribuidora teve aprovada no processo tarifário, é preciso converter esses valores em tarifas a serem cobradas dos consumidores. A definição das tarifas tem por intuito promover incentivos aos consumidores para que façam melhor uso dos recursos energéticos e da rede. O “cardápio” de tarifas atualmente oferecido aos consumidores é resumido em quatro modalidades tarifárias:

- **Azul.** Os consumidores pertencentes ao Grupo A (Alta Tensão), nos subgrupos A1, A2 e A3 obrigatoriamente devem ser tarifados por essa modalidade. Ela é opcional aos subgrupos A3a e A4. Essa modalidade tem cobrança binômia – uma parte é volumétrica e outra é por demanda contratada –, com diferenciação por posto tarifário – horário de ponta e fora de ponta.^[O horário de ponta é o período de 3 horas consecutivas nos dias úteis onde o carregamento da rede é mais elevado. Usualmente, isso ocorria entre 18-21h. Entretanto, com a adoção maciça pelos consumidores de aparelhos de refrigeração do ar, já é possível observar em muitas regiões a ponta da curva de carga ocorrendo de tarde. Entretanto, o regulador ainda não atualizou a definição do horário de ponta para a realidade atualmente retratada nas curvas de carga.] A cobrança da energia (TE) é feita em termos volumétricos (R\$/MWh) com valores diferenciados por posto tarifário na ponta (P) e fora da ponta (FP), sendo a ponta mais cara. A TUSD é cobrada de duas formas: em função da demanda contratada (R\$/kW), sendo essa parte associada aos custos de infraestrutura de transporte de energia, sejam eles de transmissão ou distribuição – essa parcela da TUSD é conhecida como TUSD Demanda, com valores diferenciados por posto tarifário –, já a segunda é função da energia consumida (R\$/MWh) e está associada aos custos de perdas elétricas e encargos setoriais. Essa parcela também é conhecida como TUSD Perdas e Encargos e não possui diferenciação por posto tarifário.
- **Verde.** Os consumidores pertencentes ao Grupo A, nos subgrupos A3a e A4 podem optar por essa modalidade. Aqui também há cobrança binômia – uma parte é volumétrica e outra é por demanda contratada –, com diferenciação por posto tarifário – horário de ponta e fora de ponta. Nessa modalidade, a cobrança da energia (TE) também é feita em termos volumétricos (R\$/MWh) com valores diferenciados por posto tarifário na ponta (P) e fora da ponta (FP), sendo a ponta mais cara. A TUSD também é cobrada de duas formas. A TUSD Demanda é cobrada em R\$/kW, sem diferenciação por posto tarifário. Entretanto, a parcela da TUSD cobrada em função da energia consumida (R\$/MWh) não está associada apenas aos custos de perdas elétricas e encargos setoriais: parte dos custos com infraestrutura de transporte foram alocadas ao posto tarifário de ponta – razão pela qual a TUSD em R\$/MWh na ponta é muito mais elevada que a TUSD, em R\$/MWh, fora da ponta.
- **Convencional.** Aplicável apenas aos consumidores do Grupo B (Baixa Tensão), de forma mandatória. A cobrança é monômia, dado que toda a tarifa é cobrada de forma volumétrica, sem diferenciação por posto tarifário. Tanto a cobrança da energia (TE) como a da TUSD é feita em termos volumétricos (R\$/MWh) sem valores diferenciados por posto tarifário.
- **Branca.** Aplicável de forma opcional aos consumidores do Grupo B, exceto para consumidores de baixa renda e iluminação pública. A cobrança é monômia, dado que toda a tarifa é cobrada de forma volumétrica, mas com diferenciação por posto tarifário. É importante comentar que a modalidade Branca traz mais um posto tarifário, o intermediário, que corresponde a hora que antecede e a hora que sucede o posto de ponta. Tanto a cobrança da energia (TE) como a da TUSD é feita em termos volumétricos (R\$/MWh) sem valores diferenciados por posto tarifário.

### Bandeiras Tarifárias

Desde janeiro de 2015 entrou em vigor a figura das Bandeiras Tarifárias. Estas consistem em um mecanismo onde ao final de cada mês as condições de suprimento são avaliadas, e dependendo da expectativa de exposição dos geradores hidrelétricos ao mercado de curto prazo no mês seguinte, uma Bandeira Tarifária é acionada e a essa Bandeira está associado um adicional tarifário que é cobrado nas tarifas de energia dos consumidores cativos.

Essa expectativa de exposição dos geradores hidrelétricos ao mercado de curto prazo é mensurada em termos do PLD esperado para o mês seguinte e do GSF (_Generation Scaling Factor_), que representa a razão entre a geração hidrelétrica (nesse caso, esperada) total do sistema e a garantia física desse mesmo conjunto de usinas.

Esse adicional tarifário representa a expectativa da ANEEL de quais serão os custos variáveis^[Os custos variáveis são custos associados com ESS, EER, combustível de térmicas despachadas, resultado da liquidação da energia gerada pelas usinas térmicas contratadas por disponibilidade na CCEE e resultado da liquidação dos créditos de energia das usinas hidrelétricas com contratos de cotas ou que repactuaram o risco hidrológico, na CCEE.] a serem incorridos pelas distribuidoras, em determinados cenários hidrológicos.

Se a Bandeira acionada for a Verde, não há um adicional tarifário associado, pois _espera-se_ que a previsão de custos variáveis incluídas nas tarifas de energia homologadas, serão suficientes para cobrir os custos variáveis reais. Em outras palavras, na estimativa de custos que a ANEEL realiza para calcular a tarifa de energia homologada, as projeções de custos são feitas para o cenário de custo mais elevado _antes_ do acionamento da Bandeira Tarifária seguinte, ou seja, antes do acionamento da Bandeira Amarela.

Por outro lado, se a Bandeira acionada for a Amarela, há um adicional de 18,74 R\$/MWh a ser cobrado dos consumidores. Já se a Bandeira Vermelha (patamar 1) for acionada, o adicional cobrado dos consumidores será de 39,71 R\$/MWh. Por último, se a Bandeira Vermelha (patamar 2) for acionada, o adicional será de 94,92 R\$/MWh. Em todas essas Bandeiras, _espera-se_ que a previsão de custos variáveis incluídas nas tarifas de energia homologadas, não será suficiente para cobrir os custos variáveis reais e, portanto, os valores adicionais proveem recursos extras às distribuidoras.

Excepcionalmente, no ano de 2021, foi criada a Bandeira Escassez Hídrica, com a finalidade de custear com recursos da bandeira tarifária os custos excepcionais do acionamento de usinas térmicas e da importação de energia. Essa determinação foi feita pela Câmara de Regras Excepcionais para Gestão Hidroenergética (CREG),  com a cobrança da bandeira ficando no valor de 142,00 R\$/MWh. Essa cobrança vale para todos os consumidores do Sistema Interligado Nacional de setembro de 2021 a abril de 2022, com exceção dos beneficiários da tarifa social. 


## Estudos e projeções de longo prazo

A EPE cumpre sua finalidade de braço técnico de estudos do setor energético produzindo relatórios e planos de expansão a respeito do setor elétrico. Por se tratar de um *valuation* de uma empresa do setor, é importante ponderar a respeito das ações tomadas e o parecer de *experts* a respeito do futuro do setor como um todo, a fim de aprimorar nossas estimativas da taxa de crescimento.

São os dois principais estudos, nesse sentido, (1) o Plano Nacional de Energia; (2) e o Plano Decenal de Expansão de Energia.

### Plano Nacional de Energia (PNE)

O PNE é um conjunto de estudos que dão suporte ao desenho da estratégia de longo prazo do governo em relação à expansão do setor de energia. A estratégia, por sua vez, consiste em um conjunto de recomendações e diretrizes a serem seguidas na definição das ações e iniciativas a serem implementadas ao longo do horizonte de tempo prescrito. A revisão do PNE deve ser conduzida sempre que houver necessidade de alteração na estratégia de longo prazo do tomador de decisão relevante, sejam por razões ordinárias ou extraordinárias.

Os PNEs têm relação com os PDEs. Embora haja similaridades, o PNE é um instrumento de planejamento com atribuições distintas do PDE. Em primeiro lugar, o PNE é um documento com visão mais estratégica. Neste contexto, seu enfoque consiste em embasar o posicionamento do governo de modo a orientar e direcionar as estratégias dos agentes do setor de forma a se atingir os objetivos gerais da expansão no longo prazo, com adequação dos recursos, com confiabilidade, modicidade e sustentabilidade. Além disso, o PNE é o alicerce a partir do qual todos os Planos, Políticas, Programas e Iniciativas são elaborados. O PNE é, portanto, um farol que orienta para onde os PDEs devem indicar a expansão do setor de energia no horizonte decenal. Por fim, enquanto o PDE trabalha com um cenário de referência e análises de sensibilidade, anualmente revisto, o PNE deve tratar com mais cenários.

No caso, foi feito o estudo do PNE 2050 [@epe2020], e assim será entregue um pequeno sumário executivo do mesmo a seguir.

Foram elaborados dois grandes cenários, formando um cone de incertezas para o desenho da estratégia de longo prazo: o primeiro, chamado Desafio da Expansão, reflete requisitos de expansão do setor de energia para atendimento a um crescimento da demanda de energia mais expressivo. No segundo, chamado de Estagnação, analisam-se as consequências de um cenário em que o consumo de energia per capita mantém-se inalterado ao longo de todo o período. O foco do relatório está voltado para o cenário Desafio da Expansão.

Os estudos do PNE apontam para um potencial energético de quase 280 bilhões de tep (toneladas equivalentes de petróleo) no horizonte até 2050. A demanda cresce de 300 milhões de tep para 600 milhões de tep e, ao longo de trinta e cinco anos, essa trajetória representa uma demanda de energia total acumulada do período equivalente a pouco menos de 15 bilhões de tep. Tamanha discrepância entre potencial de recursos e a demanda de energia estimada gera uma situação distinta daquela vivida ao longo especialmente da metade do século XX, quando o País viveu grandes crises de energia. Dessa forma, imagina-se uma administração da abundância.

O cenário Desafio da Expansão considera algumas premissas, que serão levadas em conta para o uso no estudo de caso. São essas: (1) crescimento médio de PIB de 3.1% a.a. e 2.8% de PIB per capita; (2) a população brasileira manterá a tendência de crescer a taxas cada vez menores; (3) o consumo potencial de energia elétrica do País pode atingir até 3 vezes o patamar do ano base; (4) a demanda de energia elétrica a ser atendida por geração centralizada cresce até 2.5 vezes em relação aos valores do ano base, mesmo com crescimento de geração distribuída (GD), autoprodução, energia solar térmica e eficiência energética no período; (5) e o consumo de energia e de eletricidade per capita aumenta, a despeito da contribuição da eficiência energética no horizonte até 2050.

### Plano Decenal de Expansão de Energia (PDE)

O PDE tem o intuito de indicar as perspectivas, sob a ótica do Governo, da expansão do setor de energia no horizonte de dez anos, dentro de uma visão integrada para os diversos energéticos. Tal visão permite, então, extrair importantes elementos para o planejamento do setor, com benefícios em termos de aumento de confiabilidade, redução de custos de produção e mitigação de impactos ambientais.

Como o PDE tem intuitos mais operacionais do que estratégicos, serão utilizadas as premissas e estudos do PNE para nortear as decisões do presente *valuation*.
