# Conclusão

Nesta seção, faremos algumas conclusões a respeito dos métodos de _valuation_ realizados, assim como um comparativo entre eles, finalizando assim o estudo.

O valor intrínseco encontrado através do DCF é consideravelmente alto relativo ao preço atual do ativo devido a diversos fatores, a elucidar alguns:

1. **Baixa correlação do ativo com o IBOV.** Como foi observado, a correlação do ativo com o índice Bovespa é consideravelmente baixa, representando assim, dentro da teoria do CAPM, uma necessidade de retorno menor, devido à sua menor volatilidade relativa ao mercado.
2. **Crise hídrica no estado do Paraná.** Desde julho de 2019, com agravamento em março de 2020, até o momento de escrita, o estado passa por uma das piores estiagens da história. Por se tratar de uma companhia com matriz elétrica predominantemente hidráulica, a empresa acaba por perder então espaço no ambiente de contratação livre, assim como ser exposta a um índice mais alto de inadimplência no ambiente regulado, tendo em vista os acréscimos nas contas de luz.
3. **Possíveis interferências públicas.** Assim como ocorreu com a Companhia de Saneamento do Paraná em 2020, existe a possibilidade da Agência Reguladora de Serviços Públicos Delegados do Paraná (Agepar) suspender revisões tarifárias. Continuando pela analogia, a agência suspendeu 3 vezes o reajuste de saneamento e, ao final, reduziu o valor de 9.62% para 5.11%. Cabe comentar, o acionista majoritário é o próprio estado do Paraná. Naturalmente, o poder público demonstra assim uma possível falha de governança, ao passo que nem sempre as ações do governo estarão alinhadas com os interesses dos acionistas.

Dessa forma, uma confluência de fortes fatores colaboram para fazer com que uma empresa, mesmo que sólida em termos financeiros, possua um preço baixo relativa aos seus pares.

Curiosamente, o resultado do DCF é uma cifra maior do que a do modelo de desconto de dividendos, e isso é devido, em grande parte, ao fato do custo da dívida acrescido do _tax shield_ ser consideravelmente menor do que o custo de capital próprio. Como as proporções de cada tipo de capital na estrutura da empresa é próximo a 50/50, isso faz com o que o WACC seja consideravelmente reduzido.

De qualquer forma, ambos os métodos demonstraram que a ação, em sua cotação atual, mostra-se **desvalorizada** relativo ao seu valor intrínseco. Entretanto, como visto, esta análise é consideravelmente mais demorada do que uma análise de múltiplos. 

Assim, para não realizar estudos de _valuation_ intrínseco para cada empresa aberta, cada uma com suas peculiaridades e em diferentes setores com diferentes normas e regulamentos, é interessante filtrar possíveis desvalorizações com uma breve análise de múltiplos para um setor com pares comparáveis, como foi feito no _valuation_ relativo, para depois seguir com um estudo mais profundo de _valuation_ intrísenco, para finalmente determinar se um ativo está ou não de fato desvalorizado, conforme premissas determinadas.

Como ramificações futuras desse estudo, podem ser realizados os mesmos métodos, entretanto ao invés de possuir uma visão do agregado, fazer uma espécie de _valuation_ "soma das partes", levando em conta as peculiaridades de cada braço da companhia – geração, transmissão, comercialização e distribuição. Adicionalmente, não necessariamente precisa ser da mesma _holding_ – no caso, a Copel –, mas para outras _holdings_ do setor elétrico, também.

Outra possibilidade seria de explorar outros métodos de _valuation_ relativo, tendo em vista que o trabalho se limitou a discorrer apenas sobre análise por múltiplos. Poderia ser feito um estudo a respeito do uso de múltiplos de preço-alvo, em que se define um preço teto até onde, baseado em múltiplos, com o qual seria possível ainda comprar determinado ativo e ainda assim esperar um retorno satisfatório.