---
title: "Untitled"
author: "Rafael Pinto de Freitas"
date: "26/01/2022"
output: pdf_document
---

# Dados tarifários 9 jul

```{r, tab.pos = "H", echo = FALSE, message = FALSE}
library(tidyverse)
library(knitr)
library(kableExtra)

kable(
  tibble(
    `Descrição` = c("B1 - Baixa Renda, até 30 kWh", "B1 - Baixa Renda, entre 31 e 100 kWh", "B1 - Baixa Renda, entre 101 e 220 kWh", "B1 - Baixa Renda, superior a 220 kWh", "B1 - Residencial", "B2 - Cooperativa de Eletrificação Rural", "B2 - Irrigação e Aquicultura em horário especial", "B2 - Rural", "B2 - Serviço Público de Irrigação Rural", "B3 - Água, Esgoto e Saneamento", "B3 - Demais Classes", "B3 - Poder Público Estadual", "B4A - Iluminação Pública", "B4B - Iluminação Pública"),
    `Convencional.TE` = c(0.09441, 0.23076, 0.34614, 0.38460, 0.3846, 0.30066, 0.12615, 0.31537, 0.29229, 0.34998, 0.38460, 0.26973, 0.21153, 0.23076),
    `Convencional.TUSD` = c(0.06628, 0.16201, 0.24301, 0.27001, 0.36837, 0.28797, 0.12083, 0.30207, 0.27996, 0.33522, 0.36837, 0.25835, 0.20260, 0.22103),
    `Branca.FP.TE` = c(0, 0, 0, 0, 0.36533, 0.28559, 0.11982, 0.29956, 0.27765, 0.33245, 0.36533, 0.25622, 0, 0),
    `Branca.FP.TUSD` = c(0, 0, 0, 0, 0.27639, 0.21606, 0.09065, 0.22664, 0.21006, 0.26347, 0.28953, 0.20306, 0, 0),
    `Branca.I.TE` = c(0, 0, 0, 0, 0.36533, 0.28559, 0.29956, 0.29956, 0.27765, 0.33245, 0.36533, 0.25622, 0, 0),
    `Branca.I.TUSD` = c(0, 0, 0, 0, 0.53043, 0.41465, 0.43495, 0.43495, 0.40313, 0.51855, 0.56984, 0.39965, 0, 0),
    `Branca.P.TE` = c(0, 0, 0, 0, 0.36533, 0.28559, 0.29956, 0.29956, 0.27765, 0.33245, 0.36533, 0.25622, 0, 0),
    `Branca.P.TUSD` = c(0, 0, 0, 0, 0.78446, 0.61325, 0.64326, 0.64326, 0.59618, 0.77365, 0.85016, 0.59625, 0, 0)
  ),
  caption = "Tarifas aplicadas à baixa tensão.",
  format = "latex",
  booktabs = TRUE,
  col.names = NULL,
  align = "c",
  longtable = TRUE
  ) %>%
  column_spec(1, width = "8em") %>%
  kable_styling(
    latex_options = c("HOLD_position", "repeat_header"),
    repeat_header_text = "\\textit{(continuação)}",
    font_size = 10
  ) %>%
  add_header_above(
    header = c(" " = 1, "TE" = 1, "TUSD" = 1, "TE" = 1, "TUSD" = 1, "TE" = 1, "TUSD" = 1, "TE" = 1, "TUSD" = 1)
  ) %>%
  add_header_above(
    header = c(" " = 3, "Fora de Ponta" = 2, "Intermediário" = 2, "Ponta" = 2)
  ) %>%
  add_header_above(
    header = c(" " = 1, "Convencional" = 2, "Branca" = 6),
    bold = TRUE
  ) %>%
  footnote(general = "Consumo medido em R$/kWh.",
           general_title = "Nota: ",
           title_format = "italic",
           footnote_as_chunk = TRUE)
```

```{r, tab.pos = "H", echo = FALSE, message = FALSE}
library(tidyverse)
library(knitr)
library(kableExtra)

kable(
  tibble(
    `Grupo` = c("A1", "A2", "A3", "A3", "A3a", "A3a", "A3a", "A3a", "A3a", "A3a", "A3a", "A3a", "A3a", "A4", "A4", "A4", "A4", "A4", "A4", "A4", "A4", "A4", "AS", "AS", "AS", "AS"),
    `Modalidade` = c("Azul", "Azul", "Azul", "Azul - Poder Público Estadual", "Azul", "Azul - Cooperativas Autorizadas", "Azul - Poder Público Estadual", "Azul - Rural", "Verde", "Verde - Aquicultura e Irrigação em Horário Especial", "Verde - Cooperativas Autorizadas", "Verde - Poder Público Estadual", "Verde - Rural", "Azul", "Azul - Cooperativas Autorizadas", "Azul - Poder Público Estadual", "Azul - Rural", "Verde", "Verde - Aquicultura e Irrigação em Horário Especial", "Verde - Cooperativas Autorizadas", "Verde - Poder Público Estadual", "Verde - Rural", "Azul", "Azul - Poder Público Estadual", "Verde", "Verde - Poder Público Estadual"),
    `FP.Demanda.TUSD` = c(6.21, 9.19, 10.65, 7.47, 22.41, 16.76, 15.72, 21.06, 22.41, 22.41, 16.75, 15.72, 21.06, 22.41, 16.83, 15.72, 21.06, 22.41, 22.41, 16.83, 15.72, 21.06, 22.73, 15.94, 22.73, 15.94),
    `FP.Consumo.TE` = c(0.36533, 0.36533, 0.36533, 0.25622, 0.36533, 0.27323, 0.25622, 0.34341, 0.36533, 0.10960, 0.27323, 0.25622, 0.34341, 0.36533, 0.27433, 0.25622, 0.34341, 0.36533, 0.10960, 0.27433, 0.25622, 0.34341, 0.36533, 0.25622, 0.36533, 0.25622),
    `FP.Consumo.TUSD` = c(0.07884, 0.08712, 0.08816, 0.06183, 0.11436, 0.08553, 0.08021, 0.10750, 0.11436, 0.03431, 0.08553, 0.08021, 0.10750, 0.11436, 0.08587, 0.08021, 0.10750, 0.11436, 0.03431, 0.08587, 0.08021, 0.10750, 0.15601, 0.10941, 0.15601, 0.10941),
    `P.Demanda.TUSD` = c(6.52, 22.35, 24.23, 16.99, 50.35, 37.66, 35.31, 47.33, 22.41, 22.41, 16.75, 15.72, 21.06, 50.35, 37.81, 35.31, 47.33, 22.41, 22.41, 16.83, 15.72, 21.06, 98.93, 69.38, 22.73, 15.94),
    `P.Consumo.TE` = c(0.59656, 0.59656, 0.59656, 0.41839, 0.59656, 0.44617, 0.41839, 0.56077, 0.59656, 0.59656, 0.44617, 0.41839, 0.56077, 0.59656, 0.44796, 0.41839, 0.56077, 0.59656, 0.59656, 0.44796, 0.41839, 0.56077, 0.59656, 0.41839, 0.59656, 0.41839),
    `P.Consumo.TUSD` = c(0.07884, 0.08712, 0.08816, 0.06183, 0.11436, 0.08553, 0.08021, 0.10750, 1.33891, 1.33891, 1.00137, 0.93903, 1.25858, 0.11436, 0.08587, 0.08021, 0.10750, 1.33891, 1.33891, 1.00539, 0.93903, 1.25858, 0.15601, 0.10941, 2.56357, 1.79793)
  ),
  caption = "Tarifas aplicadas à alta tensão.",
  format = "latex",
  booktabs = TRUE,
  col.names = NULL,
  align = "c",
  longtable = T
  ) %>%
  column_spec(2, width = "8em") %>%
  kable_styling(
    latex_options = c("HOLD_position", "repeat_header"),
    repeat_header_text = "\\textit{(continuação)}",
    font_size = 10
  ) %>%
  add_header_above(
    header = c("Grupo" = 1, "Modalidade" = 1, "TUSD" = 1, "TE" = 1, "TUSD" = 1, "TUSD" = 1, "TE" = 1, "TUSD" = 1)
  ) %>%
  add_header_above(
    header = c(" " = 2, "Demanda" = 1, "Consumo" = 2, "Demanda" = 1, "Consumo" = 2)
  ) %>%
  add_header_above(
    header = c(" " = 2, "Fora de Ponta" = 3, "Ponta" = 3),
    bold = TRUE
  ) %>%
  footnote(general = "Demanda e consumo medidos, respectivamente, em R$/kW e R$/kWh.",
           general_title = "Nota: ",
           title_format = "italic",
           footnote_as_chunk = TRUE)
```
